services:
  web:
    build: ./web
    container_name: web
    ports:
      - "8080:80"

    depends_on:
      emulator:
        condition: service_healthy

  android:
    build: ./android
    container_name: android
    volumes:
      - ./target:/app/target
    command: >
      sh -c "
        if ![ -f /app/target/app.apk ]; then
          ./gradlew assembleDebug
          ./gradlew copyApkToTarget
        fi
      "

  install-frida-server:
    build: ./install-frida-server
    container_name: install-frida-server
    depends_on:
      emulator:
        condition: service_healthy

    environment:
      FRIDA_URL: https://github.com/frida/frida/releases/download/17.9.1/frida-server-17.9.1-android-x86_64.xz
      FRIDA_SERVER: /data/local/tmp/frida-server
      EMULATOR_HOST: emulator
      EMULATOR_PORT: "5555"

    volumes:
      - ./target:/target

  emulator:
    image: budtmo/docker-android:emulator_11.0
    container_name: emulator

    devices:
      - /dev/kvm:/dev/kvm

    ports:
      - "6080:6080" # web vnc
      - "5555:5555" # adb
      - "5554:5554" # console
      - "9000:9000" # web logs

    environment:
      EMULATOR_DEVICE: "Samsung Galaxy S10"
      WEB_VNC: "true"
      WEB_LOG: "true"

    healthcheck:
      test:
        ["CMD-SHELL", "sh", "-c", "cat device_status | grep READY || exit 1"]
      interval: 20s
      timeout: 2m
      retries: 10
      start_period: 30s

  run-frida-server:
    build: ./run-frida-server
    container_name: run-frida-server
    restart: "no"

    depends_on:
      emulator:
        condition: service_healthy
      install-frida-server:
        condition: service_completed_successfully

    command: ["sh", "-c", "adb shell '/data/local/tmp/frida-server &'"]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh",
          "-c",
          "adb shell 'ps | grep frida-server' | grep -q frida-server || exit 1",
        ]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 10s

  sentry:
    build: ./sentry
    container_name: sentry

    depends_on:
      emulator:
        condition: service_healthy
      install-frida-server:
        condition: service_completed_successfully
      run-frida-server:
        condition: service_healthy

    environment:
      APP_PACKAGE: "com.example.bachelorproject"
