services:
  web:
    build: ./web
    container_name: web
    ports:
      - "8080:80"

    depends_on:
      emulator:
        condition: service_healthy

  android:
    build: ./android
    container_name: android
    volumes:
      - ./target:/app/target
    command: >
      sh -c "
        if [ ! -f /app/target/app.apk ]; then
          ./gradlew assembleDebug
          ./gradlew copyApkToTarget
        fi
      "

  run-frida-server:
    build: ./run-frida-server
    container_name: run-frida-server
    restart: "no"

    volumes:
      - ./target:/target

    depends_on:
      emulator:
        condition: service_healthy
      android:
        condition: service_completed_successfully

    environment:
      FRIDA_SERVER: /data/local/tmp/frida-server
      ADB_HOST: emulator
      ADB_PORT: "5555"
      FRIDA_URL: https://github.com/frida/frida/releases/download/17.9.1/frida-server-17.9.1-android-x86_64.xz

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "adb connect emulator:5555 >/dev/null 2>&1 || true; adb -s emulator:5555 shell pgrep -f frida-server >/dev/null 2>&1",
        ]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 45s

  emulator:
    image: budtmo/docker-android:emulator_11.0
    container_name: emulator

    devices:
      - /dev/kvm:/dev/kvm

    ports:
      - "6080:6080" # web vnc
      - "5555:5555" # adb
      - "5554:5554" # console
      - "9000:9000" # web logs

    environment:
      EMULATOR_DEVICE: "Samsung Galaxy S10"
      WEB_VNC: "true"
      WEB_LOG: "true"

    healthcheck:
      test: ["CMD-SHELL", "adb connect 127.0.0.1:5555 >/dev/null 2>&1;"]
      interval: 20s
      timeout: 2m
      retries: 30
      start_period: 30s

  sentry:
    build: ./sentry
    container_name: sentry

    depends_on:
      emulator:
        condition: service_healthy
      run-frida-server:
        condition: service_healthy

    environment:
      APP_PACKAGE: "com.example.bachelorproject"
      URL: "http://web/"
